-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Tempo de geração: 24-Mar-2023 às 20:14
-- Versão do servidor: 10.4.22-MariaDB
-- versão do PHP: 7.4.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `estudos_mentoria`
--
CREATE DATABASE IF NOT EXISTS `estudos_mentoria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `estudos_mentoria`;

-- --------------------------------------------------------

--
-- Estrutura da tabela `pessoas`
--

DROP TABLE IF EXISTS `pessoas`;
CREATE TABLE IF NOT EXISTS `pessoas` (
  `id` int(36) NOT NULL AUTO_INCREMENT,
  `nome` varchar(100) NOT NULL,
  `idade` tinyint(250) NOT NULL,
  `cidade` varchar(50) NOT NULL,
  `estado` varchar(2) NOT NULL,
  `genero_autoidentificacao` varchar(50) NOT NULL,
  `pronomes` varchar(50) NOT NULL,
  `participacao` varchar(2000) NOT NULL,
  `link_perfil_linkedin` varchar(100) DEFAULT NULL,
  `porque_esta_aqui` varchar(2000) DEFAULT NULL,
  `bio` varchar(3000) DEFAULT NULL,
  `data_apresentacao` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8mb4;

--
-- Extraindo dados da tabela `pessoas`
--

INSERT INTO `pessoas` (`id`, `nome`, `idade`, `cidade`, `estado`, `genero_autoidentificacao`, `pronomes`, `participacao`, `link_perfil_linkedin`, `porque_esta_aqui`, `bio`, `data_apresentacao`) VALUES
(1, 'Nina Kitsu', 37, 'São Paulo', 'SP', 'Pessoa agênera transfeminina', 'ELA/DELA', 'Mentoria Programação', 'https://www.linkedin.com/in/ninetails/', 'Queria muito retribuir a comunidade tech e melhor ainda se posso ser inclusiva 🏳️‍⚧️ Logo amei a oportunidade e a coincidência do projeto ter surgido bem agora ❤️', 'Olá, sou a Nina Kitsu, paulistana, agênera transfeminina com pronomes ela/dela e aro ace (demi-demi), monogâmica e comprometida. Já desisti de duas graduações, uma era matemática 😱 Comecei com PHP mas hoje minha especialidade é frontend e tenho mais de 10 anos na área, ultimamente trabalhando em alguns ecommerces do mercado.\r\n\r\nEm São Paulo participo de diversos eventos e meetups de tech. Atualmente trabalho num lugar onde aceitam e respeitam meu nome social ❤️\r\n\r\nNos tempos livres gosto de ficar assistindo animes, jogar e sair com amigos. Minha preferência musical é mais por eletrônica, inclusive frequentava muitos festivais de música eletrônica comerciais por aqui.\r\n\r\nAhh sim, e eu mando bastante carinhas... :3', '2023-03-01 03:23:00'),
(2, 'Ayssa', 23, 'Brasília', 'DF', 'Não-binário agênero', 'ELE/DELE', 'Mentorande Programação', NULL, 'Tenho procurado oportunidades de me capacitar com o objetivo de me inserir no mercado de trabalho.', 'Moro em Brasília desde criança mas sou Manauara de nascença e coração ❤️ Vegano, não-monogamico bissexual com dois amores maravilhoses, graduando em Ciência da Computação final de 2023 se tudo ocorrer como planejado. Comecei estudando Engenharia Mecatrônica na UnB mas vi que não era pra mim e transferi depois de 3 anos. Tenho estudado front-end, por conta da  função que exerço no meu estágio, mas sonho em um dia ser cientista de dados. E em fazer uma graduação em história também!\r\nEu gosto de tudo um pouco: anime/mangá, música de todos os gêneros, fotografia, filmes (gosto muito de horror), literatura, dormir, comer, fazer nada, jogar um Minecraft. Ultimamente tenho me interessado por escultura e praticado Muay Thai. ', '2023-03-01 04:08:00'),
(3, 'Bev Feitosa', 24, 'Fortaleza', 'CE', 'Pessoa trans não-binária agênero', 'ELU/DELU', 'Mentoria Programação', 'https://linkedin.com/in/bevfeitosa', 'Contribuir com conhecimentos pra comunidade, aprender novas skills e conhecer novas pessoas :3', 'Eu sou formade em engenharia de materiais com experiência em laboratório com cerâmicas e vim pro frontend ano passado através de uma bolsa de estudos no Todas as Letras (inclusive recomendo entrarem lá), na mesma época que saí da casa dos meus pais. Atualmente eu tbm procuro minha primeira oportunidade de trabalho na área!\r\n\r\nSou bem ative no LinkedIn e tenho uma rede de apoio trans bem consolidada lá, eu acho. Se conectem comigo!\r\n\r\nDe experiência extra: já fiz live na twtich, editei vídeos pra uma página no instagram da universidade, já dei aula de reforço pra minha tia que tava fazendo mestrado em economia e já cuidei muito de criança pq tenho um irmão mais novo (mas não moro mais com ele nem meus pais).\r\n\r\nDe hobbie eu gosto de cozinhar (atualmente tô aprendendo a fazer pães, pizza e esfihas, mas amo fazer pudins e empadas 💗), jogar umas coisinhas online (lol, valorant, wakfu, genshin e mais) e aprender coreografias (especialmente de kpop).\r\n\r\nAh, eu não sou muito de séries/filmes, assisto mesmo só drag race, mas AMO o mundo da música. Escuto muita coisa diferente e experimental, principalmente de artistas trans. Sim eu sou fã da ARCA.\r\n\r\nADORO MEMES, sou muito ligadinhe nisso.\r\n\r\nE é isso, espero ter ótimas trocas com vocês e é sempre um prazer conhecer pessoas novas ✌️', '2023-03-01 05:51:00'),
(4, 'Nico', 24, 'Ribas', 'MS', 'Transmasculino não binário', 'ELE/DELE', 'Mentorande Programação', 'https://www.linkedin.com/in/nico-rocha', 'Sempre estou a procura de oportunidades que possam me ajudar nesse começo de carreira como Desenvolvedor Junior. Vejo essa mentoria como uma forma de fazer parte de uma comunidade com pessoas que posso me identificar e conectar, e aproveitar cada aprendizado.', 'Sou formado em Design, sempre gostei e ainda gosto da área, principalmente a area de UI/UX, tanto que fiquei na dúvida em qual área da mentoria escolher, mas no momento decidi focar em Desenvolvimento Front-end. \r\n\r\nSempre me interessei pela área de programação, cheguei a fazer alguns cursos básicos durante minha graduação, mas só fui ver essa área como possibilidade em 2022, e foi quando me inscrevi em um bootcamp de Java Full Stack. Foi super intensivo, mas também super gratificante o aprendizado. Foi uma experiência bem realista, com imersões feitas para simular de fato como é o trabalho e dia-a-dia de um dev jr.\r\n\r\nGosto muito de música, joguinhos pra passar raiva online de vez em quando, vtubers, arte, bookbinding, ainda desenho as vezes, e agora estou curtindo minha rotina de treino.', '2023-03-01 16:27:04'),
(5, 'Marcelle', 26, 'Rio de Janeiro', 'RJ', 'Mulher cis', 'ELA/DELA', 'Mentoria Programação', 'http://www.linkedin.com/in/marcelle-vargas', 'Meu objetivo aqui é ajudar a tornar a área de TI mais acessível e diversa (de verdade)', 'Olá, Meu nome é Marcelle, estou terminando a graduação em Ciências Matemáticas e da Terra - UFRJ. ✨️ Sou uma engenheira de software apaixonada por programação e pelo universo de TI. Eu estou sempre compartilhando coisas sobre esse universo, se vc quiser pode procurar por @marcellecode em quase todas as redes', '2023-03-01 18:05:32'),
(6, 'Rilary', 19, 'Brasília', 'DF', 'Travesti', 'ELA/DELA', 'Mentorande Programação', NULL, 'Bom, eu estou aqui pois senti um interesse pela área, por ver que tem crescido bastante ultimamente e acho que é uma grande oportunidade para mim. E pelo ambiente de aula ser para pessoas trans, faz tudo ser bem mais confortável para mim, e eu tô adorandooo isso.', 'Oioii, meu nome é Rilary, tenho 19 anos e eu sou uma travesti multiartista e moradora de Ceilândia. Antes de morar aqui passei por várias casas e várias cidades, acabei enfrentando vários problemas familiares, e por conta disso tive que abandonar os estudos por um tempo, atualmente estou no último ano do ensino médio, e tudo que eu busco hoje e ter uma estabilidade de lar e financeira, e os estudos pra mim é uma grande forma de alcançar isso. Pra quem quiser me acompanhar ou conversar comigo (amo conhecer gente nova) meu Instagram é: @Rilarymarquez', '2023-03-01 22:05:34'),
(7, 'Hugo', 27, 'São Paulo', 'SP', 'Transmasculino intersexo', 'ELE/DELE', 'Mentorande UI/UX', 'https://www.linkedin.com/in/carvalh6p/', 'Acho importante estar sempre me atualizando com novas técnicas, ferramentas e fazer networking que é importante pra fortalecer geral ', 'Sou Mineiro de nascença mas virei uma mistura com Goiano e Brasiliense, residindo em SP por enquanto, formado e com carreira de designer gráfico, trabalho autônomo tem 8 anos (behance é meu portfólio online) e presto serviço aqui e ali em algumas empresas, formado tbm em técnico em informática e o pacote todo do curso me animou bastante a retornar aos estudos e ampliar minha rede de apoio transcentrada', '2023-03-02 18:11:50'),
(8, 'Francielle', 33, 'Brasília', 'DF', 'Mulher trans', 'ELA/DELA', 'Mentoria Programação', 'https://www.linkedin.com/in/francisco-ramos-bb515a181/', 'Tive muito interesse pelo fato de poder ajudar, interagir e conhecer mais pessoas trans como eu', 'Gosto muito de programação e trabalho como programadora desde 2019. Sou mais backend mas já trabalhei como full stack e atualmente sou concursada em TI.\r\n\r\nComecei minha transição tem cerca de 1 ano e comecei a hormonizar tem cerca de 6 meses. Por enquanto estou no armário pra quase todos e pretendo sair aos poucos.\r\n\r\nGosto muito de jogos, principalmente RPGs, música eletronica e outras nerdices. Muito prazer, espero que gostem da mentoria e espero conhecer mais pessoas!', '2023-03-04 13:28:36'),
(9, 'Bernardo', 21, 'Russas', 'CE', 'Homem trans', 'ELE/DELE', 'Mentorande Programação', NULL, 'Acredito que aprender move e tira a gente de muitos lugares, e que conhecimento é revolucionário e muda um tanto de coisas ao mesmo tempo que te faz crescer, então é uma oportunidade pra crescer e aprender algo novo, uma chance de se dar conhecimento, uma vez que você quer aprender e tem quem te ensine.', 'Sou cearense e como um bom cearense, sou apaixonado por praia e sol, um dia nublado pra mim é o mesmo que um dia triste. Apesar da expectativa de vida ser lá embaixo e eu nem precisar explicar sobre isso, sou um cara que ama muito viver, então ter essa expectativa nunca vai me parar. Gosto muito do novo e de sair da minha zona de conforto. Nas horas vagas curto muito cantar mpb e cozinhar. Acho que por cima é isso.\r\nEspero ter uma troca massa com todo mundo, como já estou tendo, e é isso. 🫶🏽', '2023-03-07 14:47:11'),
(10, 'Lucas', 24, 'Aparecida de Goiânia', 'GO', 'Não binário', 'ELE/DELE', 'Mentorande Programação', 'https://www.linkedin.com/in/lucas-henrique-0312a2183', 'Busco estabilidade financeira. Sempre fui apaixonado pelo universo da tecnologia, porém sempre foi algo muito distante da minha realidade.', 'Sou nascido e criado em Goiás, tenho uma filha linda de 3 aninhos. Iniciei a faculdade de psicologia, mas pelas dificuldades da vida de um proletariado adiar esse sonho. Gosto de lê livros, vê filmes, vídeos e séries sobre True Crime', '2023-03-07 22:32:43'),
(11, 'Yudi Santos', 30, 'Recife', 'PE', 'Homem trans', 'ELE/DELE', 'Mentorande UX/UI', NULL, 'Então eu estou muito confuso sobre que área seguir dentro da tecnologia e se eu quero seguir também, estou aberto a ouvir e aprender e vê se é isso que eu quero pra mim zzz', 'Desde que me intendo por gente foi trabalhando da gestão pública quando conseguia e militância de forma não remunerada, pq quem é militante sabe o corre que é. Mas também toco e escrevo projetos voltando para a militância. Mudar tá sendo difícil, pq requer tempo estudar o novo e só não entra no juízo muitas vezes.', '2023-03-07 18:05:12'),
(12, 'Miguel', 21, 'Brasília', 'DF', 'Homem trans', 'ELE/DELE', 'Mentorande Programação', NULL, 'Porque vi como uma oportunidade de me ajudar a ingressar no mercado de trabalho, e uma oportunidade para conhecer mais pessoas trans', NULL, '2023-03-08 12:08:07'),
(13, 'JuCo', 25, 'Taguatinga', 'DF', 'Não-Binárie', 'ELE/DELE', 'Mentorande UI/UX', 'https://www.linkedin.com/in/ju-costa-12492a15a/', 'Na verdade eu não sabia muito bem como funcionava uma mentoria mas quando vi que também abordaria UI/UX fiquei bastante interessado, já tenho contato superficial com o seguimento (meu pai trabalha na área) e achei que seria interessante conseguir aprender num ambiente com pessoa Trans. Depois de entender como funciona a mentoria tô bem animado, gostando muito das aulas e de conhecer pessoas incríveis da comunidade.', 'Nasci em Taguatinga e nunca morei em outro lugar, as vezes fico com medo de estar criando raiz demais por aqui kk. Tenho dois gatinhos mas sou cat e dog lover não tem como escolher um. Gosto MUITO de desenhar, tem sido minha terapia por muitos anos apesar dessa definição ser meio controversa hoje por eu ter transformado esse “hobbie” em profissão. \r\n\r\nFiquei sabendo do projeto pelo Saulo que é mentor de programação aqui no transformação tamém, fomos colegas de olimpíada do conhecimento na área de design gráfico em 2015. Depois de passar pela OC não consegui ingressar em nenhuma universidade pública mas segui trabalhando na área (e com ilustração) em algumas empresas mas majoritariamente como freelancer. Hoje tô na reta final de uma graduação em Design de Moda mas meu oficio principal é a tatuagem (quem quiser conhecer meu trabalho meu @ no ig é juquittoo). Mirando em vários lugares até encontrar o que vai ser mais estável kkkkk, acho que é isso. \r\n\r\nTô muito animado de tá participando do projeto como aluno, muito impressionado com a organização e o conhecimento de todes aqui !! Um xero ❤️', '2023-03-08 14:32:09'),
(14, 'Ary', 25, 'Florianópolis', 'SC', 'Não binário', 'ELE/DELE', 'Mentoria UI/UX', 'https://www.linkedin.com/in/ariely-suptitz-4a72151b6/', 'Fui convidado pelo coletivo para ajudar como mentore e pra aprender coletivamente, conseguir novas amizades e conhecer mais gente linda.', 'Oi, eu sou o Ary, sou uma pessoa autista e não binária vindo do interior do RS, que trabalha hoje com edição de vídeo e branding. Gosto muito de fotografia analógica, vinis, de desenhar e escrever. Qualquer dúvida ou desabafo é só vir falar comigo!', '2023-03-10 01:51:03'),
(15, 'Lua Brainer', 23, 'Rio de Janeiro', 'RJ', 'Mulher trans', 'ELA/DELA', 'Mentorande Programação', 'https://www.linkedin.com/in/lua-brainer-365a8620b', 'Quero melhorar minha área profissional', 'Olá meu nome é lua brainer sou moradora do complexo da maré no Rio de Janeiro,atualmente produtora cultural dentro da cidade carioca é estudante da universidade federal do Rio de Janeiro.', '2023-03-10 19:11:11'),
(16, 'Jefferson', 37, 'Florianópolis', 'SC', 'Homem cis', 'ELE/DELE', 'Mentoria UI/UX', 'https://www.linkedin.com/in/jeffersonalex', 'Sou um homem negro hétero cis, em constante aprendizado para mudar o mundo que infelizmente me foi apresentado até então. Por isso estou aqui com todes para um aprendizado mutuo.', 'Venho de uma família de retirantes nordestinos, de Pernambuco para São Paulo, pobre de não ter o que comer na adolência - período em que também fui flanelinha. Nesta família eu fui o único que conseguiu passar do ensino fundamental e através do investimento do meu tempo em educação eu construí um presente confortável, em uma profissão que adoro. Batalhando contra todas os problemas sociais do meu cenário (racismo, xenofobia e outras cositas más), venho evoluindo na área de design de produto digital.', '2023-03-10 21:44:49'),
(17, 'Espedito', 27, 'Fortaleza', 'CE', 'Homem cis', 'ELE/DELE', 'Mentoria UI/UX', 'https://www.linkedin.com/in/espeditoroza/', 'Como pessoa LGBTQIA+ busco tanto na minha trajetória acadêmica quanto profissional criar oportunidades para garantir voz a pessoas LGBTQIA+. Acredito que é fundamental aumentar a diversidade na área da tecnologia e enxergo no projeto TRANSformação Digital uma oportunidade de fazer isso.', 'Sou de Fortaleza/CE e trabalho como UX/UI Designer. Já tive experiência nos nichos de educação, finanças, segurança pública, direitos humanos e saúde. Para além do trabalho eu adoro fotografia, jogos de tabuleiro, ir à praia, nadar, viajar, cozinhar, ler e me reunir com os amigos em absolutamente qualquer lugar.\r\n\r\nAh, também faço parte de um projeto que tá começando agora que é o Re.tifica, um aplicativo que visa ajudar no processo de retificação de nome e/ou gênero para pessoas trans e travestis: https://retifica.app/ \r\n\r\nE qualquer dúvida, podem me chamar que estou à disposição de todes', '2023-03-11 17:08:48');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
